language: java
jdk:
  - oraclejdk8
sudo: required
services:
- docker

install: true
script: mvn package
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ${ACCESS_TOKEN}
  file: target/bluefin.jar
  on:
    tags: true
    all_branches: true